In [ ]:
#가상환경

print('Hello')

# 클래스

In [ ]:
class Student:
    population = 0 #클래스 변수 (공유)
    
    def __init__(self, name, age): #생성자
        self.name = name #인스턴스 변수
        self.age = age
        Student.population += 1

    # 매서드
    def hello(self):
        print(f'{self.name}님 안녕하세요')

In [37]:
# 상속
class NewStudent(Student):

    #새로운 매서드
    def study(self):
        print(f'{self.name}님이 공부해요')
    #매서드 오버라이딩(기존의 매서드 재정의)
    def hello(self):
        print(f'{self.name}님이 반갑게 인사해요')

In [38]:
std1 = Student('최수빈', 27)
std2 = Student('최연준', 28)
std3 = NewStudent('최범규', 25)

In [39]:
std3.study()
std3.hello()

최범규님이 공부해요
최범규님이 반갑게 인사해요


In [40]:
std1.hello() 
print(Student.population)

최수빈님 안녕하세요
14


In [6]:
#넘파이 설치

import numpy as np

In [8]:
np.__version__

'2.5.3'

In [7]:
alist = [1,2,3,4,5]
print(alist)

[1, 2, 3, 4, 5]


In [47]:
ar = np.array(alist)

In [51]:
print(type(ar))
print(ar)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [48]:
print(type(alist))

<class 'list'>


In [54]:
blist = [1, '2', 2.2, 4]

In [57]:
ar1 = np.array(blist, dtype='int') #dtype = 데이터타입 변경

In [58]:
ar1.ndim

1

In [ ]:
ar1.shape #열이 4개이다.

(4,)

In [73]:
ar2 = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ar2.ndim #2차원
ar2.shape #3행 4열

(3, 4)

In [ ]:
ar3 = ar2.reshape(2, -1, 3) #행, 뎁스(하나 줄임), 열
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

(alist == 2) | (blist > 8)

array([False,  True, False,  True,  True])

In [81]:
import time

time.time()

1789614896.156188

In [85]:
size = 1000000
py_list = list(range(size))
np_array = np.arange(size)

In [86]:
start_time = time.time()
[i * 2 for i in py_list]
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
np_array * 2
end_time = time.time()
print(end_time - start_time)

0.12937331199645996
0.005018949508666992


In [ ]:
alist = [[0, 1, 2], 
         [3, 4, 5]]

In [93]:
alist[0][:2]

[0, 1]

In [95]:
[alist[0][1], alist[1][1]]

[1, 4]

In [100]:
blist = np.array(alist)
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [107]:
blist[-1, -1]

np.int64(5)

In [108]:
blist[0,:2]

array([0, 1])

In [ ]:
blist[[0,1],[1,1]] # 행, 열

array([1, 4])

In [118]:
blist[:,1]

array([1, 4])

In [1]:
print('Hello')

Hello


In [9]:
a = np.array([1,2,3])
b = np.array([10, 20, 30])

print(2*a + b)
print(a==2)
print(b>10)
print((a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [12]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0, 0])
print(a[0, 1])
print(a[1, 2])

0
1
5


In [18]:
a = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7]])
print(a[0][:3]) #행 슬라이싱
print(a[:, 1]) #열 슬라이싱
print(a[:, :2])

[0 1 2]
[1 5]
[[0 1]
 [4 5]]


In [19]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

In [ ]:
a[idx] #True인것만 출력됨

array([0, 2, 4, 6, 8])

In [22]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#idx = np.array([0, 2, 4, 6, 8])
idx = np.array([0,0,0,1,1,1])

a[idx]

array([0, 0, 0, 1, 1, 1])

In [32]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[:, [0, 3]]


array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [33]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [37]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [41]:
x[x%4 ==1]

array([ 1,  5,  9, 13, 17])

In [44]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

# 판다스